version: '3.8'

services:
  coffee-store-server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coffee-store  # Update with your MongoDB URI
    depends_on:
      - mongo

  coffee-store-client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000  # Update with your server URL
    depends_on:
      - coffee-store-server

  mongo:
    image: mongo
    ports:
      - "27017:27017"
